version: '3'

services:
  nginx:
    image: "lavenderflowerdew/alpine-nginx"
    environment:
      - CLUSTER_CONF=nowfcgi~now~nowfcgi:9000;wylie~wylie~wylie:9000;
    ports:
      - "80:80"
    links:
      - nowfcgi
      - wylie
    networks:
      - web_net
      - pandoc_net
  nowfcgi:
    build:
      context: ${PWD}/now
      dockerfile: Dockerfile
    image: "now:latest"
    ports:
      - "9000:9000"
    networks:
      - pandoc_net
  wylie:
    build:
      context: ${PWD}/wylie
      dockerfile: Dockerfile
    image: "wylie:latest"
    ports:
      - "9001:9000"
    networks:
      - pandoc_net
networks:
  web_net:
  pandoc_net:
