version: '3'

services:
  editor:
    build:
      context: ${PWD}/editor
      dockerfile: Dockerfile
    image: "editor:latest"
    environment:
      - CLUSTER_CONF=nowfcgi~now~nowfcgi:9000;wylie~wylie~wylie:9000;pandoc~pandoc~pandoc:9000;tex~tex~tex:9000;
    ports:
      - "80:80"
    depends_on:
      - nowfcgi
      - wylie
      - pandoc
      - tex
    networks:
      pandoc_net:
        aliases:
          - editor
          - nginx
      web_net:
  nowfcgi:
    build:
      context: ${PWD}/now
      dockerfile: Dockerfile
    image: "now:latest"
    ports:
      - "9000:9000"
    networks:
      pandoc_net:
        aliases:
          - nowfcgi
  wylie:
    build:
      context: ${PWD}/wylie
      dockerfile: Dockerfile
    image: "wylie:latest"
    ports:
      - "9001:9000"
    networks:
      pandoc_net:
        aliases:
          - wylie
  pandoc:
    build:
      context: ${PWD}/pandoc
      dockerfile: Dockerfile
    image: "pandoc:latest"
    ports:
      - "9002:9000"
    networks:
      pandoc_net:
        aliases:
          - pandoc
  tex:
    build:
      context: ${PWD}/tex
      dockerfile: Dockerfile
    image: "now:latest"
    ports:
      - "9003:9000"
    networks:
      pandoc_net:
        aliases:
          - tex
networks:
  web_net:
  pandoc_net:
