version: '3'

services:
  nginx:
    image: "lavenderflowerdew/alpine-nginx"
    environment:
      - CLUSTER_CONF=nowfastcgi~now~nowfastcgi:9000;fastcgi2~test2~fastcgi2:9000;
    ports:
      - "80:80"
    links:
      - nowfastcgi
      - fastcgi2
    networks:
      - web_net
      - pandoc_net
  nowfastcgi:
    build:
      context: ${PWD}/now
      dockerfile: Dockerfile
    image: "now:latest"
    ports:
      - "9000:9000"
    networks:
      - pandoc_net
  fastcgi2:
    image: "lavenderflowerdew/alpine-perl-fastcgi"
    ports:
      - "9001:9000"
    networks:
      - pandoc_net
networks:
  web_net:
  pandoc_net:
